### ISSUE TITLE
issues when maximized

### ISSUE THREAD

**Issue by megabugman** [dmtr99/wInspector#1]
hi,
there are some issues when maximized:
1) maximize the window, close, re-start script, -> window is not fully maximized
2) maximize the window, toggle controlList, -> window size becomes smaller and smaller

cheers

bonus bug:
incorrect status text
![statustext](https://user-images.githubusercontent.com/17204819/178352443-1ece50d8-8b73-46a9-b617-6ccd74de17c6.png)
the text should read click or left click

**Comment by dmtr99** [comment]
These issues should be fixed now, thanks a lot for the testing.
The bug that the window became smaller and smaller was indeed annoying.

I tried to make the gui flexible with a new concept, I already works quite well, but is not 100% bugfree.
Maximizing still causes some minor issues, I will open a separate issue for it.
(when reloading the gui in maximized position, the gui will now reopen in a fake maximized state)
