### ISSUE TITLE
How do you use this? 

### ISSUE THREAD

**Issue by eabase** [dmtr99/wInspector#13]
Can you please provide some instructions on how to use this, and a few screenshots? 
Thank you.

**Comment by dmtr99** [comment]
The Readme file is now updated. 
I tried to make this program as flexible and intuitive as possible.

**Comment by eabase** [comment]
Hi @dmtr99 
I still don't know how to install this. Can you provide the steps? 
I don't have AuthoHot key, so the steps would be much more helpful.

**Comment by dmtr99** [comment]
You can download https://www.autohotkey.com/download/ahk-v2.exe to install autohotkek v2
And than just open wInspector.ahk, this should run the program
