### ISSUE TITLE
Error: Expected a Number but got a String.

### ISSUE THREAD

**Issue by megabugman** [dmtr99/wInspector#2]
whenever I click somewhere in the ControlList I get this error:
![error](https://user-images.githubusercontent.com/17204819/178354235-73e5378f-d571-4a04-bbd7-f7bc85eff680.png)

PS: as wInspect is always on top, (topmost) the dialog will not be visible by default

**Comment by dmtr99** [comment]
Thanks for pointing this out.

Fixed in latest version, added exception to do nothing if no row is selected.
