### ISSUE TITLE
PID in hexadecimal

### ISSUE THREAD

**Issue by megabugman** [dmtr99/wInspector#3]
not sure why, task manager applications show pid in decimal:
![PID](https://user-images.githubusercontent.com/17204819/178355621-04c5bddf-0263-4fce-b652-0b99b107dc1c.png)

**Comment by dmtr99** [comment]
Thanks for the feedback.

I guess that is just a matter of personal preference.
I have added the option ID Hex to the settings menu to be able to switch between them.
