### ISSUE TITLE
Access denied errors

### ISSUE THREAD

**Issue by Lexikos** [dmtr99/wInspector#8]
If I uncheck "Visible" in the window list, I get several "Access is denied" errors whenever the list refreshes.

> ▶	1394: win_process := WinGetProcessName(win_id)
> ▶	1409: ProcessPath := WinGetProcessPath(win_id)

These most likely relate to windows with the following titles: NvSvc, UxdService, NvContainerWindowClass00001758, DWM Notification Window.

The two "Nv" windows presumably relate to Nvidia software.

For the process name, I would suggest something simple like
```AutoHotkey
win_process := ""
try win_process := WinGetProcessName(win_id)
```
The process path appears to be only used for the icon; I would suggest
```AutoHotkey
try
    mapIL[win_id] := IL_Add(ImageWinList, WinGetProcessPath(win_id))
catch
    mapIL[win_id] := 0
```

**Comment by dmtr99** [comment]
Thanks for the imput, this is now fixed.
