### ISSUE TITLE
Run with UI access

### ISSUE THREAD

**Issue by Lexikos** [dmtr99/wInspector#9]
Launching wInspector with "Run with UI access" (i.e. AutoHotkey64_UIA.exe) should enable it to control windows of higher-integrity processes, without having to run wInspector as admin.

Unfortunately, when running wInspector with UI access, all of the child GUIs end up as separate top-level windows.

I have never observed this before, but can reproduce it with a minimal script, so it is not unique to wInspector. The (very strange) limitation appears to be that `+Parent` will fail to set the parent window if:
  - The process is running with UI access (there is no difference in the actual code, just `uiAccess="true"` in the manifest, and a digital signature on the exe).
  - The new parent window has `+AlwaysOnTop`.
  - The child window already exists (i.e. there is no problem *creating* a window with `+Parent` in the initial options).
  - The child window does not have `+AlwaysOnTop` (*before* `+Parent`).

Setting options after creating a window is less efficient anyway, so I would suggest simply passing `ChildOpt` to the several `Gui()` calls for the child windows and removing the `oSection.Opt(ChildOpt)` call.

Alternatives:
  - Move `+AlwaysOnTop` before `+Parent`.
  - Remove `+AlwaysOnTop` from the initial `Gui()` call for the parent window (it's redundant anyway) and set it based on `oSet.WinAlwaysOnTop` *after* `+Parent` is applied for the child windows.

**Comment by dmtr99** [comment]
I made the changes, please check if this fixes the problem.

**Comment by Lexikos** [comment]
Yes, it works.
